// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36Fpa5KPK-BRwYIky5bAd_h13brqpKRk',
    appId: '1:316727667727:web:18739b5283329e1f27477a',
    messagingSenderId: '316727667727',
    projectId: 'undercontrolled-f1948',
    authDomain: 'undercontrolled-f1948.firebaseapp.com',
    storageBucket: 'undercontrolled-f1948.firebasestorage.app',
    measurementId: 'G-LLVMK3F2L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfZYb8Y_tWtZDDS2CwrhJy1Cx1lmD173Y',
    appId: '1:316727667727:android:90844d17c14c011027477a',
    messagingSenderId: '316727667727',
    projectId: 'undercontrolled-f1948',
    storageBucket: 'undercontrolled-f1948.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1t-Wi4TDn59SRlS-GDoVHi9s53DNfy6k',
    appId: '1:316727667727:ios:c2daca1cd7ae4ea827477a',
    messagingSenderId: '316727667727',
    projectId: 'undercontrolled-f1948',
    storageBucket: 'undercontrolled-f1948.firebasestorage.app',
    iosBundleId: 'com.undercontrolled.underControlled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1t-Wi4TDn59SRlS-GDoVHi9s53DNfy6k',
    appId: '1:316727667727:ios:c2daca1cd7ae4ea827477a',
    messagingSenderId: '316727667727',
    projectId: 'undercontrolled-f1948',
    storageBucket: 'undercontrolled-f1948.firebasestorage.app',
    iosBundleId: 'com.undercontrolled.underControlled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA36Fpa5KPK-BRwYIky5bAd_h13brqpKRk',
    appId: '1:316727667727:web:23fdf8ac771cb73827477a',
    messagingSenderId: '316727667727',
    projectId: 'undercontrolled-f1948',
    authDomain: 'undercontrolled-f1948.firebaseapp.com',
    storageBucket: 'undercontrolled-f1948.firebasestorage.app',
    measurementId: 'G-E1J08B4F7W',
  );

}